### ISSUE TITLE
Update Support Responsibility Matrix to make clear removal of devices is Tier 1

### ISSUE THREAD

**Issue by Deadtired78** [trustgrid/docs#265]
Add a line at the end of the bullet list for Example tasks that say:
* Disabling and removal nodes, clusters and related configuration (e.g. routes) when no longer needed

**Comment by Deadtired78** [comment]
This already got done.  Something about how it was done didn't close the issue

**Comment by xav32290** [comment]
Gotcha, disregarding then.

Working on updating the docs with Boris to detail the upgrade process next.

-Xavier J Herrera
