### ISSUE TITLE
Document event payload elements and how to use Cel expressions

### ISSUE THREAD

**Issue by Deadtired78** [trustgrid/docs#362]
We need to document the event payload elements with some examples so that customers can use the new Cel expressions appropriately.

**Comment by Deadtired78** [comment]
We also need to add a page that provides common examples of expressions you might want to use and different operators and functions we think people might want to use. 
And we need to explain how the event payload is mapped to the cel context.  E.g. how nodeName becomes ctx.node.name

**Comment by terrbear** [comment]
I think we're good now https://docs.trustgrid.io/docs/alarms/alarm-filters/#cel-expressions
